package com.example.hakupivkirja.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

@Entity(
  tableName = "pisto_states",
  foreignKeys = [
    ForeignKey(
      entity = TrackEntity::class, // Parent entity
      parentColumns = ["id"],      // Primary key column in TrackEntity
      childColumns = ["trackId"],  // Foreign key column in PistoStateEntity
      onDelete = ForeignKey.CASCADE, // Optional: Deletes pisto_states if the parent track is deleted
      onUpdate = ForeignKey.CASCADE  // Optional: Updates trackId if the parent track's id is updated
      )
  ]
)
data class PistoStateEntity(
  @PrimaryKey(autoGenerate = true) // Id is primary key and it is autogenerated
  val id: Long = 0,
  @ColumnInfo(name = "trackId") // Ensure this column name matches childColumns
  val trackId: Long, // Foreign key to Track
  val pistoIndex: Int, // Index of the pisto in the track
  val type: String, // "Default", "Tyhja", "MM"
  val help: String?, // Use String for UI input, convert to Int for database
  val praise: String?, // Use String for UI input, convert to Int for database
  //val comeToMiddle: Boolean?, // Is the dog supposed to do sisääntulo or not
  // Fields for Bark alarm type (nullable)
  val barkAmount: Int? = null,
  // Fields for Roll alarm type (nullable)
  val decoyPraisesDirectly: Boolean? = null,
  val isRollSolid: Boolean? = null,
  val rollPositionWithDecoy: String? = null, // Where the roll is if not solid
  val isClosed: Boolean? = false // Is the hide plain or closed
)